#!/bin/sh

user=${1?"The user is required"}
ca_crt=${2?"The ca.crt is required"}
client_crt=${3?"The user.crt is required"}
client_key=${4?"The user.key is required"}

cat << EOF
client
dev tun
remote localhost
resolv-retry infinite
nobind
persist-key
persist-tun
verb 1
port 1194
proto udp
comp-lzo
remote-cert-tls server
ca ${ca_crt}
cert ${client_crt}
key ${client_key}
EOF

